<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container65Jh6D7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container65Jh6D7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container65Jh6D7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container65Jh6D7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container65Jh6D7\srcDevDebugProjectContainer(array(
    'container.build_hash' => '65Jh6D7',
    'container.build_id' => '223f4517',
    'container.build_time' => 1543159044,
), __DIR__.\DIRECTORY_SEPARATOR.'Container65Jh6D7');
