<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCLWLr7T\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCLWLr7T/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCLWLr7T.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCLWLr7T\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCLWLr7T\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CLWLr7T',
    'container.build_id' => '7343d50d',
    'container.build_time' => 1543101815,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCLWLr7T');
